### ISSUE TITLE
community.general.kubevirt_vm has moved to community.kubevirt.kubevirt_vm

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/molecule-kubevirt#11]
Hi !

FYI the kubevirt modules are being moved out of community.general and into their own collection under [community.kubevirt](https://github.com/ansible-collections/community.kubevirt), see changelog: https://github.com/ansible-community/ansible-build-data/blob/main/2.10/CHANGELOG-v2.10.rst#community-general

They'll continue to work from their old location for a while but we'll need to use the new location eventually in places like https://github.com/jseguillon/molecule-kubevirt/blob/520ebdc0d9a5f0e27ce9e151bc9f707331a4856b/molecule_kubevirt/playbooks/create.yml#L42-L43 and https://github.com/jseguillon/molecule-kubevirt/blob/520ebdc0d9a5f0e27ce9e151bc9f707331a4856b/molecule_kubevirt/playbooks/destroy.yml#L8-L9

**Comment by jseguillon** [comment]
Hi @dmsimard, 
Thanks a lot for this information ! 

Do you know if this change also apply to ansible 2.9 ? If possible I'd like the driver to be compatible with both 2.9 and 2.10.

**Comment by jseguillon** [comment]
Hi @dmsimard 
I  did some updates and CI is green again on newly created "main" branch replacing old "master" 

Would you like to review or can I close ?

**Comment by jseguillon** [comment]
Closed: community.kubevirt is on its way to be deprecated. version >= 0.0.5 no more requires this collection
